In [ ]:
import pandas as pd
import os
import kagglehub

In [ ]:
path = kagglehub.dataset_download("aslanahmedov/walmart-sales-forecast")
print("Dataset downloaded to:", path)

Dataset downloaded to: /kaggle/input/walmart-sales-forecast

## Data Loading

In [ ]:
# Load CSV files
train = pd.read_csv(os.path.join(path, "train.csv"))
test = pd.read_csv(os.path.join(path, "test.csv"))
features = pd.read_csv(os.path.join(path, "features.csv"))
stores = pd.read_csv(os.path.join(path, "stores.csv"))

In [ ]:
print("Train:")
train.head(5)

Train:

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [ ]:
print("Features:")
features.head(5)

Features:

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

In [ ]:
print("Stores:")
stores.head(5)

Stores:

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

## Understanding the Data

In [ ]:
datasets = {
    "Train": train,
    "Features": features,
    "Stores": stores
}

####Dimensions

In [ ]:
print("DIMENSIONS:")
print('-' * 20)

for name, dataset in datasets.items():
    print(f"{name}: {dataset.shape}")

DIMENSIONS:
--------------------
Train: (421570, 5)
Features: (8190, 12)
Stores: (45, 3)

####Dataset Summary

In [ ]:
print("SUMMARY:")
print('-' * 20)

for name, dataset in datasets.items():
    print(f"\n\n{name}:")
    dataset.info()

SUMMARY:
--------------------


Train:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  object
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), object(1)
memory usage: 13.3+ MB


Features:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         8190 non-null   int64
 1   Date          8190 non-null   object
 2   Temperature   8190 non-null   float64
 3   Fuel_Price    8190 non-null   float64
 4   MarkDown1     4032 non-null   float64
 5   MarkDown2     2921 non-null   float64
 6   MarkDown3     3613 non-null   float64
 7   MarkDown4     3464 non-null   float64
 8   MarkDown5     4050 non-null   float64
 9   CPI           7605 non-null   float64
 10  Unemployment  7605 non-null   float64
 11  IsHoliday     8190 non-null   bool
dtypes: bool(1), float64(9), int64(1), object(1)
memory usage: 712.0+ KB


Stores:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Store   45 non-null     int64
 1   Type    45 non-null     object
 2   Size    45 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.2+ KB

=> No NULL Values!

####Statistical Summary

In [ ]:
train.describe()

               Store           Dept   Weekly_Sales
count  421570.000000  421570.000000  421570.000000
mean       22.200546      44.260317   15981.258123
std        12.785297      30.492054   22711.183519
min         1.000000       1.000000   -4988.940000
25%        11.000000      18.000000    2079.650000
50%        22.000000      37.000000    7612.030000
75%        33.000000      74.000000   20205.852500
max        45.000000      99.000000  693099.360000

In [ ]:
features.describe()

,Store,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment
count,8190.000000,8190.000000,8190.000000,4032.000000,2921.000000,3613.000000,3464.000000,4050.000000,7605.000000,7605.000000
mean,23.000000,59.356198,3.405992,7032.371786,3384.176594,1760.100180,3292.935886,4132.216422,172.460809,7.826821
std,12.987966,18.678607,0.431337,9262.747448,8793.583016,11276.462208,6792.329861,13086.690278,39.738346,1.877259
min,1.000000,-7.290000,2.472000,-2781.450000,-265.760000,-179.260000,0.220000,-185.170000,126.064000,3.684000
25%,12.000000,45.902500,3.041000,1577.532500,68.880000,6.600000,304.687500,1440.827500,132.364839,6.634000
50%,23.000000,60.710000,3.513000,4743.580000,364.570000,36.260000,1176.425000,2727.135000,182.764003,7.806000
75%,34.000000,73.880000,3.743000,8923.310000,2153.350000,163.150000,3310.007500,4832.555000,213.932412,8.567000
max,45.000000,101.950000,4.468000,103184.980000,104519.540000,149483.310000,67474.850000,771448.100000,228.976456,14.313000

In [ ]:
stores.describe()

           Store           Size
count  45.000000      45.000000
mean   23.000000  130287.600000
std    13.133926   63825.271991
min     1.000000   34875.000000
25%    12.000000   70713.000000
50%    23.000000  126512.000000
75%    34.000000  202307.000000
max    45.000000  219622.000000

## Data Preprocessing

####Date Formatting

In [ ]:
for df in [train, features, test]:
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [ ]:
for name, df in zip(["train", "features", "test"], [train, features, test]):
    print(f"{name} Date dtype:", df["Date"].dtype)
    print(f"{name} Date nulls after conversion:", df["Date"].isna().sum())
    print()

train Date dtype: datetime64[ns]
train Date nulls after conversion: 0

features Date dtype: datetime64[ns]
features Date nulls after conversion: 0

test Date dtype: datetime64[ns]
test Date nulls after conversion: 0

####Merge Datasets

Train Set

In [ ]:
train_merged = train.merge(features, on=["Store", "Date"], how="left")
train_merged = train_merged.merge(stores, on="Store", how="left")

In [ ]:
train_merged.shape

(421570, 17)

In [ ]:
train_merged.head(5)

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_y,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False,A,151315

Test Test

In [ ]:
test_merged = test.merge(features, on=["Store", "Date"], how="left")
test_merged = test_merged.merge(stores, on="Store", how="left")

In [ ]:
test_merged.shape

(115064, 16)

In [ ]:
test_merged.head(5)

,Store,Dept,Date,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_y,Type,Size
0,1,1,2012-11-02,False,55.32,3.386,6766.44,5147.70,50.82,3639.90,2737.42,223.462779,6.573,False,A,151315
1,1,1,2012-11-09,False,61.24,3.314,11421.32,3370.89,40.28,4646.79,6154.16,223.481307,6.573,False,A,151315
2,1,1,2012-11-16,False,52.92,3.252,9696.28,292.10,103.78,1133.15,6612.69,223.512911,6.573,False,A,151315
3,1,1,2012-11-23,True,56.23,3.211,883.59,4.17,74910.32,209.91,303.32,223.561947,6.573,True,A,151315
4,1,1,2012-11-30,False,52.34,3.207,2460.03,NaN,3838.35,150.57,6966.34,223.610984,6.573,False,A,151315

###Handling Missing Values

Train Set

In [ ]:
train_merged.isnull().sum()

Store                0
Dept                 0
Date                 0
Weekly_Sales         0
IsHoliday_x          0
Temperature          0
Fuel_Price           0
MarkDown1       270889
MarkDown2       310322
MarkDown3       284479
MarkDown4       286603
MarkDown5       270138
CPI                  0
Unemployment         0
IsHoliday_y          0
Type                 0
Size                 0
dtype: int64

In [ ]:
markdown_cols = ['MarkDown1','MarkDown2','MarkDown3','MarkDown4','MarkDown5']

In [ ]:
train_merged[markdown_cols] = train_merged[markdown_cols].fillna(0)

In [ ]:
train_merged.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday_x     0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
IsHoliday_y     0
Type            0
Size            0
dtype: int64

In [ ]:
train_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  datetime64[ns]
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday_x   421570 non-null  bool
 5   Temperature   421570 non-null  float64
 6   Fuel_Price    421570 non-null  float64
 7   MarkDown1     421570 non-null  float64
 8   MarkDown2     421570 non-null  float64
 9   MarkDown3     421570 non-null  float64
 10  MarkDown4     421570 non-null  float64
 11  MarkDown5     421570 non-null  float64
 12  CPI           421570 non-null  float64
 13  Unemployment  421570 non-null  float64
 14  IsHoliday_y   421570 non-null  bool
 15  Type          421570 non-null  object
 16  Size          421570 non-null  int64
dtypes: bool(2), datetime64[ns](1), float64(10), int64(3), object(1)
memory usage: 49.0+ MB

Test Set

In [ ]:
test_merged.isnull().sum()

Store               0
Dept                0
Date                0
IsHoliday_x         0
Temperature         0
Fuel_Price          0
MarkDown1         149
MarkDown2       28627
MarkDown3        9829
MarkDown4       12888
MarkDown5           0
CPI             38162
Unemployment    38162
IsHoliday_y         0
Type                0
Size                0
dtype: int64

Handling Markdowns

In [ ]:
test_merged[markdown_cols] = train_merged[markdown_cols].fillna(0)

Handling CPI and Unemployment

In [ ]:
# Sort test set
test_merged = test_merged.sort_values(['Store','Dept','Date'])

# Interpolate per Store-Dept combination
test_merged['CPI'] = test_merged.groupby(['Store','Dept'])['CPI'].transform(lambda x: x.interpolate(method='linear'))
test_merged['Unemployment'] = test_merged.groupby(['Store','Dept'])['Unemployment'].transform(lambda x: x.interpolate(method='linear'))

# Forward/backward fill remaining NaNs
test_merged['CPI'] = test_merged['CPI'].ffill().bfill()
test_merged['Unemployment'] = test_merged['Unemployment'].ffill().bfill()

# Reset index
test_merged.reset_index(drop=True, inplace=True)

In [ ]:
test_merged.isnull().sum()

Store           0
Dept            0
Date            0
IsHoliday_x     0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
IsHoliday_y     0
Type            0
Size            0
dtype: int64

## Encoding Categorial Data

Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder = LabelEncoder()

In [ ]:
train_merged['Type'] = encoder.fit_transform(train_merged['Type'])
test_merged['Type'] = encoder.transform(test_merged['Type'])

Boolean Encoding

In [ ]:
bool_cols = ['IsHoliday_x', 'IsHoliday_y']
for col in bool_cols:
    train_merged[col] = train_merged[col].astype(int)
    test_merged[col] = test_merged[col].astype(int)

In [ ]:
train_merged.head(5)

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_y,Type,Size
0,1,1,2010-02-05,24924.50,0,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,0,0,151315
1,1,1,2010-02-12,46039.49,1,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,1,0,151315
2,1,1,2010-02-19,41595.55,0,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,0,0,151315
3,1,1,2010-02-26,19403.54,0,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,0,0,151315
4,1,1,2010-03-05,21827.90,0,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,0,0,151315

In [ ]:
train_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  datetime64[ns]
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday_x   421570 non-null  int64
 5   Temperature   421570 non-null  float64
 6   Fuel_Price    421570 non-null  float64
 7   MarkDown1     421570 non-null  float64
 8   MarkDown2     421570 non-null  float64
 9   MarkDown3     421570 non-null  float64
 10  MarkDown4     421570 non-null  float64
 11  MarkDown5     421570 non-null  float64
 12  CPI           421570 non-null  float64
 13  Unemployment  421570 non-null  float64
 14  IsHoliday_y   421570 non-null  int64
 15  Type          421570 non-null  int64
 16  Size          421570 non-null  int64
dtypes: datetime64[ns](1), float64(10), int64(6)
memory usage: 54.7 MB

##Saving the Data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
save_path = '/content/drive/My Drive/Python Projects/Walmart Sales Forecast/data'
print("Saving in:", save_path)

Saving in: /content/drive/My Drive/Python Projects/Walmart Sales Forecast/data

In [ ]:
os.makedirs(save_path, exist_ok=True)

train_file = os.path.join(save_path, "train_merged.csv")
test_file = os.path.join(save_path, "test_merged.csv")

train_merged.to_csv(train_file, index=False)
test_merged.to_csv(test_file, index=False)

print("Files saved at:", train_file, "and", test_file)

Files saved at: /content/drive/My Drive/Python Projects/Walmart Sales Forecast/data/train_merged.csv and /content/drive/My Drive/Python Projects/Walmart Sales Forecast/data/test_merged.csv

In [ ]:
from google.cloud import storage

In [ ]:
client = storage.Client()
bucket = client.bucket("your-bucket-name")

In [ ]:
bucket.blob("train_merged.csv").upload_from_string(train_merged.to_csv(index=False), "text/csv")
bucket.blob("test_merged.csv").upload_from_string(test_merged.to_csv(index=False), "text/csv")